# Generated by Django 2.2.7 on 2020-08-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_tobuy_tosale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tobuy',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tosale',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
